---
title: "Prep metadata for subsampling with Treemmer"
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(cache=F, echo = T, warning = F, message = F, tidy = T, comment = "", dev = "svg")
```

```{r load packages}
library(tidyverse)
```

```{r data}
# dirs
project_dir <- here::here()
project_data_dir <- file.path(project_dir, "data/dataset_5__Klebsiella_pneumoniae_SLs/")
fnxs_dir <- file.path(project_dir, "methods/bin/")
# read in data
selected_clones_data <- read_tsv(
    file.path(project_dir, "data/dataset5_K_pneumo/selected_clones/selected_clones_data.tsv"),
    show_col_types = F)

source(file.path(fnxs_dir, "filtering_and_clone_selection_functions.R"))
```


```{r select clones data}
# Clone var
clone_var <- "Sublineage" 

# loop through clones
for (SL in unique(selected_clones_data[[clone_var]])) {
    SL_analyses_dir <- file.path(project_data_dir, "selected_clones", paste0("SL_", SL))
    treemmer_dir <- file.path(SL_analyses_dir, "treemmer")
    if (! dir.exists(treemmer_dir)) {
        fs::dir_create(treemmer_dir)
    }
    # get metadata for subsampling
    SL_data <- selected_clones_data %>% 
        dplyr::filter(!!rlang::sym(clone_var) == SL)
    
    SL_meta_info <- SL_data %>%
        # select diversity traits cols
        dplyr::select(sequence_id, K_locus, O_locus, cleaned_country, year) %>% 
        # assign unique values to rows with NA in country and year columns 
        # so still treated as unique 
        dplyr::mutate(cleaned_country = dplyr::if_else(is.na(cleaned_country),
                                                paste0("unknown_ctry_", row_number()),
                                                as.character(cleaned_country))) %>%
        dplyr::mutate(year = dplyr::if_else(is.na(year),
                                     paste0("unknown_yr_", dplyr::row_number()),
                                     as.character(year))) %>%
        # combine the traits into one character trait per sample
        dplyr::rowwise() %>%
        dplyr::mutate(traits = paste0(dplyr::c_across(2:dplyr::last_col()), collapse = "_")) %>% 
        dplyr::select(sequence_id, traits) %>% 
        dplyr::ungroup()
    # write clone data
    write.table(SL_meta_info,
                file.path(treemmer_dir, paste0("SL_", SL, "_treemer_meta_info.csv")),
                sep = ",", na = "", row.names = F, col.names = F)
    
}

```












